-- ======================================================================
-- pkg_activation_v2_tahap4.sql — Tahap 4: Monitoring, Audit Log, Rate Limiting, Export
--
-- PRINSIP KEAMANAN:
-- - Rate limiting server-side (5 failed attempts / 10 menit / session+IP)
-- - Audit log menyimpan SEMUA aksi aktivasi (sukses + gagal)
-- - Audit log TIDAK menyimpan plaintext code, password, token, private key
-- - Export TIDAK mengandung code_hash, plaintext code, private/public key, token
-- - Admin role diverifikasi server-side via pkg_admins + auth.uid()
--
-- ASSUMES: Tahap 1 + Tahap 2 + Tahap 3 already applied.
-- ======================================================================

-- ======================================================================
-- 1. ALTER pkg_activation_audit_logs — expand action + add columns
-- ======================================================================

-- Drop old CHECK constraint (name auto-generated by Postgres)
-- We need to find and drop the constraint, then add new one
do $$
declare
  v_constraint_name text;
begin
  select con.conname
  from pg_constraint con
  join pg_class cls on cls.oid = con.conrelid
  where cls.relname = 'pkg_activation_audit_logs'
    and con.contype = 'c'
    and pg_get_constraintdef(con.oid) like '%CREATE_CODE%'
  into v_constraint_name;

  if v_constraint_name is not null then
    execute format('alter table public.pkg_activation_audit_logs drop constraint %I', v_constraint_name);
  end if;
end$$;

-- Add new expanded CHECK constraint
alter table public.pkg_activation_audit_logs
  add constraint pkg_audit_action_check
  check (action in (
    'CREATE_CODE',
    'REVOKE_CODE',
    'VIEW_DETAIL',
    'ACTIVATE_CODE',
    'FAILED_ACTIVATION',
    'DEVICE_REPLACEMENT',
    'DEVICE_VERIFICATION_SUCCESS',
    'DEVICE_VERIFICATION_FAILED',
    'ADMIN_LOGIN',
    'ADMIN_LOGIN_FAILED',
    'ADMIN_LOGOUT',
    'EXPORT_DATA',
    'EXPORT_AUDIT_LOG',
    'RATE_LIMITED'
  ));

-- Add new columns for richer audit context
alter table public.pkg_activation_audit_logs
  add column if not exists activation_id  uuid,      -- links to pkg_activation_codes(id)
  add column if not exists device_id      text,       -- device_id from activation attempt
  add column if not exists status         text,       -- outcome status (e.g. 'ACTIVATED', 'INVALID_CODE')
  add column if not exists reason         text,       -- human-readable reason
  add column if not exists user_agent     text,       -- browser UA from request
  add column if not exists ip_address      inet;       -- client IP (best-effort)

-- Index for common queries
create index if not exists idx_pkg_audit_action    on public.pkg_activation_audit_logs (action);
create index if not exists idx_pkg_audit_status    on public.pkg_activation_audit_logs (status);
create index if not exists idx_pkg_audit_device    on public.pkg_activation_audit_logs (device_id);
create index if not exists idx_pkg_audit_ip        on public.pkg_activation_audit_logs (ip_address);

-- ======================================================================
-- 2. NEW TABLE: pkg_rate_limits — server-side rate limiting
-- ======================================================================
create table if not exists public.pkg_rate_limits (
  id            uuid        primary key default gen_random_uuid(),
  session_key   text        not null,    -- device_id or IP-based key
  ip_address    inet,
  code_attempted text,                    -- code that was tried (hashed for lookup)
  attempt_count int         not null default 1,
  first_attempt timestamptz not null default now(),
  last_attempt  timestamptz not null default now(),
  locked_until  timestamptz,              -- if set, blocks all attempts until expiry
  created_at    timestamptz not null default now()
);

create index if not exists idx_pkg_rate_session  on public.pkg_rate_limits (session_key);
create index if not exists idx_pkg_rate_ip        on public.pkg_rate_limits (ip_address);
create index if not exists idx_pkg_rate_last     on public.pkg_rate_limits (last_attempt desc);

-- RLS: no direct access for anon or authenticated. Only SECURITY DEFINER RPCs.
alter table public.pkg_rate_limits enable row level security;
-- No policies = no direct access.

-- ======================================================================
-- 3. HELPER FUNCTION: _check_rate_limit — server-side rate limiter
-- Returns true if request is allowed, false if rate-limited.
-- Also records the attempt.
-- ======================================================================
create or replace function public._check_rate_limit(
  p_session_key  text,
  p_ip_address   inet default null,
  p_code_hash    text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing   record;
  v_now        timestamptz := now();
  v_window     timestamptz := v_now - interval '10 minutes';
  v_max_attempts int := 5;
begin
  -- Check if currently locked
  select * into v_existing
  from public.pkg_rate_limits
  where session_key = p_session_key
    and last_attempt > v_window
  order by last_attempt desc
  limit 1;

  if found then
    -- Check lock
    if v_existing.locked_until is not null and v_existing.locked_until > v_now then
      return false;
    end if;

    -- Check attempt count in window
    if v_existing.attempt_count >= v_max_attempts and v_existing.first_attempt > v_window then
      -- Lock for 10 minutes from last attempt
      update public.pkg_rate_limits
      set locked_until = v_now + interval '10 minutes',
          last_attempt = v_now,
          attempt_count = attempt_count + 1
      where id = v_existing.id;
      return false;
    end if;

    -- Increment attempt
    if v_existing.first_attempt > v_window then
      -- Still in window, increment
      update public.pkg_rate_limits
      set attempt_count = attempt_count + 1,
          last_attempt = v_now,
          code_attempted = coalesce(p_code_hash, v_existing.code_attempted)
      where id = v_existing.id;
    else
      -- Window expired, reset
      update public.pkg_rate_limits
      set attempt_count = 1,
          first_attempt = v_now,
          last_attempt = v_now,
          locked_until = null,
          code_attempted = p_code_hash
      where id = v_existing.id;
    end if;
  else
    -- No existing record, create new
    insert into public.pkg_rate_limits (session_key, ip_address, code_attempted, attempt_count, first_attempt, last_attempt)
    values (p_session_key, p_ip_address, p_code_hash, 1, v_now, v_now);
  end if;

  return true;
end;
$$;

-- ======================================================================
-- 4. HELPER FUNCTION: _clear_rate_limit — reset on successful activation
-- ======================================================================
create or replace function public._clear_rate_limit(p_session_key text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.pkg_rate_limits
  where session_key = p_session_key
    and last_attempt > now() - interval '10 minutes';
end;
$$;

-- ======================================================================
-- 5. ENHANCED: activate_pkg_code — add rate limiting + audit logging
-- ======================================================================
drop function if exists public.activate_pkg_code(text, text, text, text, text, text, text, text, jsonb);

create or replace function public.activate_pkg_code(
  p_code              text,
  p_device_id         text,
  p_nama_pengguna     text default null,
  p_username          text default null,
  p_madrasah          text default null,
  p_kabupaten         text default null,
  p_role              text default null,
  p_device_info       text default null,
  p_device_public_key jsonb default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code_hash     text;
  v_code_row      record;
  v_session_key   text := coalesce(p_device_id, '');
  v_rate_ok       boolean;
  v_ip            inet := null;
  v_user_agent    text := null;
  v_result        text;
begin
  -- Hash the code for lookup
  v_code_hash := encode(digest(p_code, 'sha256'), 'hex');

  -- Rate limit check
  v_rate_ok := public._check_rate_limit(v_session_key, v_ip, v_code_hash);
  if not v_rate_ok then
    -- Audit log: rate limited
    insert into public.pkg_activation_audit_logs (
      action, device_id, status, reason, user_agent, ip_address,
      details
    ) values (
      'RATE_LIMITED', p_device_id, 'RATE_LIMITED',
      'Rate limit exceeded: 5+ failed attempts in 10 minutes',
      v_user_agent, v_ip,
      jsonb_build_object('session_key', v_session_key, 'code_hint', right(p_code, 4))
    );
    return 'RATE_LIMITED';
  end if;

  -- Validate code format (basic check)
  if p_code is null or length(p_code) < 10 then
    insert into public.pkg_activation_audit_logs (
      action, device_id, status, reason, user_agent, ip_address,
      details
    ) values (
      'FAILED_ACTIVATION', p_device_id, 'INVALID_CODE',
      'Code format invalid (too short)',
      v_user_agent, v_ip,
      jsonb_build_object('code_hint', right(coalesce(p_code, ''), 4))
    );
    return 'INVALID_CODE';
  end if;

  -- Look up code by hash
  select * into v_code_row
  from public.pkg_activation_codes
  where code_hash = v_code_hash
  for update;  -- row-level lock prevents race condition

  if not found then
    -- Code not found
    insert into public.pkg_activation_audit_logs (
      action, device_id, status, reason, user_agent, ip_address,
      details
    ) values (
      'FAILED_ACTIVATION', p_device_id, 'INVALID_CODE',
      'Code not found in database',
      v_user_agent, v_ip,
      jsonb_build_object('code_hint', right(p_code, 4))
    );
    return 'INVALID_CODE';
  end if;

  -- Check if revoked
  if v_code_row.status = 'revoked' then
    insert into public.pkg_activation_audit_logs (
      action, activation_code_id, device_id, status, reason,
      user_agent, ip_address, details
    ) values (
      'FAILED_ACTIVATION', v_code_row.id, p_device_id, 'REVOKED',
      'Code has been revoked',
      v_user_agent, v_ip,
      jsonb_build_object('code_hint', v_code_row.code_hint)
    );
    return 'REVOKED';
  end if;

  -- Check if already used
  if v_code_row.status = 'activated' then
    insert into public.pkg_activation_audit_logs (
      action, activation_code_id, device_id, status, reason,
      user_agent, ip_address, details
    ) values (
      'FAILED_ACTIVATION', v_code_row.id, p_device_id, 'ALREADY_USED',
      'Code already activated by another device',
      v_user_agent, v_ip,
      jsonb_build_object('code_hint', v_code_row.code_hint, 'existing_device', v_code_row.device_id)
    );
    return 'ALREADY_USED';
  end if;

  -- Code is valid and unused — activate it
  update public.pkg_activation_codes
  set
    status              = 'activated',
    activated_at        = now(),
    activated_by        = p_device_id,
    device_id           = p_device_id,
    device_info         = p_device_info,
    device_public_key   = p_device_public_key,
    device_key_created_at = case when p_device_public_key is not null then now() else device_key_created_at end,
    nama_pengguna       = coalesce(p_nama_pengguna, nama_pengguna),
    username            = coalesce(p_username, username),
    madrasah            = coalesce(p_madrasah, madrasah),
    kabupaten           = coalesce(p_kabupaten, kabupaten),
    role                = coalesce(p_role, role)
  where id = v_code_row.id;

  -- Clear rate limit on success
  perform public._clear_rate_limit(v_session_key);

  -- Audit log: successful activation
  insert into public.pkg_activation_audit_logs (
    action, activation_code_id, device_id, status, reason,
    user_agent, ip_address, details
  ) values (
    'ACTIVATE_CODE', v_code_row.id, p_device_id, 'ACTIVATED',
    'Code successfully activated',
    v_user_agent, v_ip,
    jsonb_build_object(
      'code_hint', v_code_row.code_hint,
      'nama_pengguna', coalesce(p_nama_pengguna, v_code_row.nama_pengguna),
      'madrasah', coalesce(p_madrasah, v_code_row.madrasah),
      'kabupaten', coalesce(p_kabupaten, v_code_row.kabupaten),
      'role', coalesce(p_role, v_code_row.role),
      'has_device_key', p_device_public_key is not null
    )
  );

  return 'ACTIVATED';
end;
$$;

-- ======================================================================
-- 6. NEW RPC: admin_list_audit_logs — filter, search, pagination
-- ======================================================================
create or replace function public.admin_list_audit_logs(
  p_action     text default null,
  p_date_from  date default null,
  p_date_to    date default null,
  p_search     text default null,
  p_page       int  default 1,
  p_limit      int  default 25
)
returns table (
  id                uuid,
  action            text,
  admin_email       text,
  activation_code_id uuid,
  activation_id     uuid,
  device_id         text,
  status            text,
  reason            text,
  user_agent        text,
  details           jsonb,
  created_at        timestamptz,
  total_count       bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_uid uuid := auth.uid();
  v_is_admin  boolean;
  v_offset    int;
begin
  select exists(select 1 from public.pkg_admins where user_id = v_admin_uid) into v_is_admin;
  if not v_is_admin then
    raise exception 'UNAUTHORIZED: pemanggil bukan admin terdaftar' using errcode = '42501';
  end if;

  v_offset := (p_page - 1) * p_limit;

  return query
  select
    a.id,
    a.action,
    au.email as admin_email,
    a.activation_code_id,
    coalesce(a.activation_id, a.activation_code_id) as activation_id,
    a.device_id,
    a.status,
    a.reason,
    a.user_agent,
    a.details,
    a.created_at,
    count(*) over() as total_count
  from public.pkg_activation_audit_logs a
  left join auth.users au on au.id = a.admin_user_id
  where (p_action is null or a.action = p_action)
    and (p_date_from is null or a.created_at >= p_date_from)
    and (p_date_to is null or a.created_at < (p_date_to + interval '1 day'))
    and (
      p_search is null or
      a.status ilike '%' || p_search || '%' or
      a.reason ilike '%' || p_search || '%' or
      a.device_id ilike '%' || p_search || '%' or
      coalesce(au.email, '') ilike '%' || p_search || '%' or
      a.action ilike '%' || p_search || '%'
    )
  order by a.created_at desc
  limit p_limit offset v_offset;
end;
$$;

-- ======================================================================
-- 7. NEW RPC: admin_activation_stats_v2 — 8 stat cards
-- ======================================================================
create or replace function public.admin_activation_stats_v2()
returns table (
  total_codes      bigint,
  unused_codes     bigint,
  activated_codes  bigint,
  revoked_codes    bigint,
  activated_today  bigint,
  activated_30d     bigint,
  device_replacements bigint,
  failed_attempts  bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_uid uuid := auth.uid();
  v_is_admin  boolean;
begin
  select exists(select 1 from public.pkg_admins where user_id = v_admin_uid) into v_is_admin;
  if not v_is_admin then
    raise exception 'UNAUTHORIZED' using errcode = '42501';
  end if;

  return query
  select
    (select count(*) from public.pkg_activation_codes) as total_codes,
    (select count(*) from public.pkg_activation_codes where status = 'unused') as unused_codes,
    (select count(*) from public.pkg_activation_codes where status = 'activated') as activated_codes,
    (select count(*) from public.pkg_activation_codes where status = 'revoked') as revoked_codes,
    (select count(*) from public.pkg_activation_codes where activated_at >= current_date) as activated_today,
    (select count(*) from public.pkg_activation_codes where activated_at >= now() - interval '30 days') as activated_30d,
    (select count(*) from public.pkg_activation_codes where replacement_for is not null) as device_replacements,
    (select count(*) from public.pkg_activation_audit_logs where action = 'FAILED_ACTIVATION' and created_at >= now() - interval '24 hours') as failed_attempts;
end;
$$;

-- ======================================================================
-- 8. NEW RPC: admin_get_suspicious_activity — recent failed attempts
-- ======================================================================
create or replace function public.admin_get_suspicious_activity(
  p_hours  int  default 24,
  p_limit  int  default 20
)
returns table (
  id             uuid,
  action         text,
  device_id      text,
  status         text,
  reason         text,
  ip_address     inet,
  created_at     timestamptz,
  details        jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_uid uuid := auth.uid();
  v_is_admin  boolean;
begin
  select exists(select 1 from public.pkg_admins where user_id = v_admin_uid) into v_is_admin;
  if not v_is_admin then
    raise exception 'UNAUTHORIZED' using errcode = '42501';
  end if;

  return query
  select
    id, action, device_id, status, reason, ip_address, created_at, details
  from public.pkg_activation_audit_logs
  where action in ('FAILED_ACTIVATION', 'RATE_LIMITED', 'DEVICE_VERIFICATION_FAILED')
    and created_at >= now() - (p_hours || ' hours')::interval
  order by created_at desc
  limit p_limit;
end;
$$;

-- ======================================================================
-- 9. NEW RPC: admin_export_data — export activation codes (NO secrets)
-- ======================================================================
create or replace function public.admin_export_data(
  p_status  text default null,
  p_role    text default null
)
returns table (
  code_hint       text,
  status          text,
  nama_pengguna   text,
  username        text,
  madrasah        text,
  kabupaten       text,
  role            text,
  device_id       text,
  device_info     text,
  created_at      timestamptz,
  activated_at    timestamptz,
  revoked_at      timestamptz,
  catatan         text
  -- NOTE: code_hash, device_public_key, replaced_activation_id, replacement_for EXCLUDED
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_uid uuid := auth.uid();
  v_is_admin  boolean;
begin
  select exists(select 1 from public.pkg_admins where user_id = v_admin_uid) into v_is_admin;
  if not v_is_admin then
    raise exception 'UNAUTHORIZED' using errcode = '42501';
  end if;

  return query
  select
    code_hint,
    status,
    nama_pengguna,
    username,
    madrasah,
    kabupaten,
    role,
    device_id,
    device_info,
    created_at,
    activated_at,
    revoked_at,
    catatan
  from public.pkg_activation_codes
  where (p_status is null or status = p_status)
    and (p_role is null or role = p_role)
  order by created_at desc;
end;
$$;

-- ======================================================================
-- 10. NEW RPC: admin_export_audit_log — export audit logs (NO secrets)
-- ======================================================================
create or replace function public.admin_export_audit_log(
  p_action     text default null,
  p_date_from  date default null,
  p_date_to    date default null
)
returns table (
  action            text,
  admin_email       text,
  activation_code_id uuid,
  device_id         text,
  status            text,
  reason            text,
  created_at        timestamptz,
  details           jsonb
  -- NOTE: details may contain code_hint but NOT code_hash, plaintext code, or private key
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_uid uuid := auth.uid();
  v_is_admin  boolean;
begin
  select exists(select 1 from public.pkg_admins where user_id = v_admin_uid) into v_is_admin;
  if not v_is_admin then
    raise exception 'UNAUTHORIZED' using errcode = '42501';
  end if;

  return query
  select
    a.action,
    coalesce(au.email, '') as admin_email,
    a.activation_code_id,
    a.device_id,
    a.status,
    a.reason,
    a.created_at,
    a.details
  from public.pkg_activation_audit_logs a
  left join auth.users au on au.id = a.admin_user_id
  where (p_action is null or a.action = p_action)
    and (p_date_from is null or a.created_at >= p_date_from)
    and (p_date_to is null or a.created_at < (p_date_to + interval '1 day'))
  order by a.created_at desc;
end;
$$;

-- ======================================================================
-- 11. ENHANCED: admin_revoke_activation_code — add audit log with reason
-- ======================================================================
-- (Already logs in Tahap 2, but now we have expanded action constraint)
-- Re-create to include revoked_reason column
-- Drop BOTH old signatures: Tahap 2 had (uuid), we need to also drop that
-- to avoid ambiguity with the new 2-arg version.
drop function if exists public.admin_revoke_activation_code(uuid);
drop function if exists public.admin_revoke_activation_code(uuid, text);

create or replace function public.admin_revoke_activation_code(
  p_code_id  uuid,
  p_reason   text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin_uid uuid := auth.uid();
  v_is_admin  boolean;
  v_code_row  record;
begin
  select exists(select 1 from public.pkg_admins where user_id = v_admin_uid) into v_is_admin;
  if not v_is_admin then
    raise exception 'UNAUTHORIZED' using errcode = '42501';
  end if;

  select * into v_code_row
  from public.pkg_activation_codes
  where id = p_code_id
  for update;

  if not found then
    raise exception 'NOT_FOUND: kode aktivasi tidak ditemukan';
  end if;

  if v_code_row.status = 'revoked' then
    raise exception 'ALREADY_REVOKED';
  end if;

  update public.pkg_activation_codes
  set status = 'revoked',
      revoked_at = now(),
      revoked_by = v_admin_uid,
      revoked_reason = coalesce(p_reason, 'Manual revocation by admin')
  where id = p_code_id;

  -- Audit log
  insert into public.pkg_activation_audit_logs (
    admin_user_id, action, activation_code_id, status, reason, details
  ) values (
    v_admin_uid, 'REVOKE_CODE', p_code_id, 'REVOKED',
    coalesce(p_reason, 'Manual revocation'),
    jsonb_build_object(
      'code_hint', v_code_row.code_hint,
      'previous_status', v_code_row.status,
      'revoked_reason', coalesce(p_reason, 'Manual revocation by admin')
    )
  );

  return 'REVOKED';
end;
$$;

-- ======================================================================
-- 12. GRANT execute on new RPCs to authenticated role
-- ======================================================================
-- New RPCs need explicit GRANT to be callable by authenticated users.
-- Helper functions (_check_rate_limit, _clear_rate_limit, _cleanup_old_rate_limits)
-- are SECURITY DEFINER and only called internally — NO GRANT to anyone.

revoke execute on function public.admin_revoke_activation_code(uuid) from public, anon, authenticated;
grant execute on function public.admin_revoke_activation_code(uuid, text) to authenticated;

grant execute on function public.admin_list_audit_logs(text, date, date, text, int, int) to authenticated;
grant execute on function public.admin_activation_stats_v2() to authenticated;
grant execute on function public.admin_get_suspicious_activity(int, int) to authenticated;
grant execute on function public.admin_export_data(text, text) to authenticated;
grant execute on function public.admin_export_audit_log(text, date, date) to authenticated;

-- Revoke direct table access to pkg_rate_limits from all roles (RLS-only + RPC-only)
revoke all on public.pkg_rate_limits from public, anon, authenticated;

-- ======================================================================
-- 13. CLEANUP: Remove old rate limit entries periodically (not automatic,
--     but admin can trigger via a cron or manual SQL)
-- ======================================================================
-- Optional: create a cleanup function
create or replace function public._cleanup_old_rate_limits()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  delete from public.pkg_rate_limits
  where last_attempt < now() - interval '1 hour'
  returning id into v_deleted;
  -- Actually count
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

-- ======================================================================
-- END OF TAHAP 4 MIGRATION
-- Apply AFTER Tahap 1 + Tahap 2 + Tahap 3.
-- ======================================================================
